### ISSUE TITLE
Flashbang Wall Clip

### ISSUE THREAD

**Issue by AnEpilepticGamer** [LongParsnip/LethalCompany-EpilepsyPatch#11]
The flash from the flashbang clips through walls. We were on Dine at the time.

**Comment by LongParsnip** [comment]
Hello, sorry I haven't had time to investigate lately. Can you please describe the exact manner this happens / happened or how to reproduce it.

Thanks.

**Comment by AnEpilepticGamer** [comment]
No worries! I was standing at the top of the staircase in the mansion.
Someone was on the other side of the wall and pulled a flashbang. The
bright white clipped through like it normally would without the mod

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LP-Atkins** [comment]
I have changed the code to disable the rendering filters as well. I am having trouble uploading it, thunderstore appears to be broken at the moment, so may take a while to get it updated in the mod manager.

**Comment by AnEpilepticGamer** [comment]
Not a problem at all! Thank you!!
