### ISSUE TITLE
Photosensitivity Option - Bees and Teleporter

### ISSUE THREAD

**Issue by AnEpilepticGamer** [LongParsnip/LethalCompany-EpilepsyPatch#2]
When you're being attacked by bees or being teleported up, there are particle effects on the screen. Any way to get rid of those?

**Comment by LongParsnip** [comment]
I have added this to the patch, please create a separate ticket for each request in future.

**Comment by AnEpilepticGamer** [comment]
Oh! I’m sorry! I had assumed they would be the same fix and didn’t want to
overwhelm

**Comment by LongParsnip** [comment]
All good, a lot of things that sound very similar will often be in completely different sections of the code.
