### ISSUE TITLE
Photosensitivity Option - Terminal Cursor

### ISSUE THREAD

**Issue by AnEpilepticGamer** [LongParsnip/LethalCompany-EpilepsyPatch#4]
The last thing I've seen is the cursor rapid blinks when you go to type in locations/store/etc. Can it be made to be static?

**Comment by LongParsnip** [comment]
This has been addressed in v1.0.9

I have chosen to hide the blinking caret from view as stopping it from blinking was causing the terminal to occasionally miss the first key stroke for some reason.

**Comment by AnEpilepticGamer** [comment]
Awesome! Thank you!
