### ISSUE TITLE
[Bug] Setting 'Disable radar booster animation' to 'false' does not work

### ISSUE THREAD

**Issue by throwitaway99** [LongParsnip/LethalCompany-EpilepsyPatch#8]
In testing, I have used just this mod & dependencies with default config (other than the aforementioned setting). Despite setting 'Disable radar booster animation' to 'false' in config, I've noticed that the animation is still not being shown, and I can only hear the sound of the radar booster.

![EpilepsyPatch-Bug](https://github.com/LongParsnip/LethalCompany-EpilepsyPatch/assets/136512585/7979bc11-596d-489d-8ae0-62e7b0340ad5)

**Comment by LongParsnip** [comment]
Thanks for the report, there was an incorrect reference to the config setting. I have updated the patch and pushed the update to thunderstore.
